# Dockerfile for database consumer
FROM python
RUN apt-get update
RUN pip install pymongo
RUN pip install pika

COPY database_consumer.py database_consumer.py

CMD ["python","-u","database_consumer.py"]