# Dockerfile for ride matching consumer
FROM python
RUN apt-get update
RUN pip install requests
RUN pip install pika

COPY ride_matching_consumer.py ride_matching_consumer.py

CMD ["python", "ride_matching_consumer.py"]